=== StudentClientServer/Lab2/Server/group.dtd
<!ELEMENT groups (group*)>

<!ELEMENT group (student*)>
<!ATTLIST group
id CDATA #REQUIRED
fakulty CDATA #REQUIRED
number CDATA #REQUIRED
>

<!ELEMENT student (subject*)>
<!ATTLIST student 
id CDATA #REQUIRED
firstname CDATA #REQUIRED
lastname CDATA #REQUIRED
groupnumber CDATA #REQUIRED
>

=== StudentClientServer/Lab2/Server/groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE group SYSTEM "group.dtd" >

<groups>
<group id="9999" fakulty="FizTeh" number="1">
<student firstname="Tom" lastname="Cruzz" groupnumber="1" enrolled="02.09.2010"/>
<student firstname="Bob" lastname="Tornton" groupnumber="1" enrolled="09.09.2010"/>
<student firstname="Phil" lastname="Richards" groupnumber="1" enrolled="08.09.2010"/>
<student firstname="John" lastname="Depp" groupnumber="1" enrolled="07.09.2010"/>

</group>
<group id="8888" fakulty="MehMat" number="2">
<student firstname="Tony" lastname="Ellias" groupnumber="2" enrolled="05.09.2010"/>
<student firstname="James" lastname="Bond" groupnumber="2" enrolled="04.09.2010"/>
<student firstname="Leonardo" lastname="Dikaprio" groupnumber="2" enrolled="04.09.2010"/>
<student firstname="Steeve" lastname="Jobs" groupnumber="2" enrolled="03.09.2010"/>

</group>
</groups>
